### ISSUE TITLE
Error - API Key is not set

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [kieraneglin/smmrize#1]
Hello @kieraneglin, I am not sure what I am doing wrong. I have;
1. become a SMMRY partner. 
2. set API access to LIMITED. 
3. configured API key obtained from SMMRY into Ruby script.

However, I get the following error;
`.rvm/gems/ruby-2.2.2/gems/smmrize-0.1.1/lib/smmrize.rb:15:in api_key': Smmrize::Defaults API Key is not set (Exception)`
Seems like it is not accepting my API key.

**Comment by arnoldtonderaimarunda** [comment]
Hi @kieraneglin 
Your **smmrize** gem worked when I changed the following code;
`Smmrize::Defaults.api_key = ENV['SMMRY_API_KEY']`
to this
`Smmrize::Defaults.api_key = 'SMMRY_API_KEY'`

It works really well - like magic! Greatly appreciate the work you and SMMRY have put in.

**Comment by kieraneglin** [comment]
@arnoldfungai, I'm amazed that someone actually used this gem! 😄

Anyway, the issue is that you probably didn't have your API key stored as an environment variable.  Generally, it's good practice to not store any API key in your source code (especially if you're checking your code into Github).  Try setting the environment variable to `SMMRY_API_KEY=xxxxxxxxx` [using this guide](http://osxdaily.com/2015/07/28/set-enviornment-variables-mac-os-x/) and using the first snippit of code.  It should work just the same, but it'll follow better practices!

**Comment by arnoldtonderaimarunda** [comment]
@kieraneglin It was a right fit for a feature I want to add to my educational twitter bot @opentxtbook A virtual learning assistant, using direct messages. Thank for tip on environment variable. Always learning. Everything is cool now.
